In [1]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
x = np.random.uniform(0.0, 1.0, 50)
x

array([ 0.30230893,  0.40299982,  0.19600766,  0.95260673,  0.40014594,
        0.93053192,  0.14911967,  0.73715523,  0.45042009,  0.93697908,
        0.38443402,  0.68981642,  0.5009628 ,  0.4972409 ,  0.57054871,
        0.33237499,  0.02351703,  0.7847522 ,  0.22582114,  0.72101949,
        0.29879473,  0.14317472,  0.25662467,  0.51491603,  0.42717013,
        0.15876602,  0.71557411,  0.11173053,  0.02950491,  0.26436662,
        0.10587588,  0.42329847,  0.99849075,  0.59712378,  0.99614796,
        0.88112761,  0.24123704,  0.79940994,  0.64215631,  0.76553985,
        0.85620818,  0.40820818,  0.53498496,  0.39651704,  0.18063347,
        0.1740208 ,  0.94374697,  0.62550074,  0.47415672,  0.12654165])

In [1]:
%load_ext rpy2.ipython

In [6]:
%load_ext oct2py.ipython

In [7]:
x = %octave [1 2; 3 4];
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [2]:
%R X=c(1,4,5,7); sd(X); mean(X)

<FloatVector - Python:0x7f87e989b508 / R:0x331fad8>
[4.250000]

In [9]:
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [10]:
 _ = %R x = c(3,4,6.7); y = c(4,6,7); z = c('a',3,4)

In [8]:
%%bash
echo "hello, stderr" >&2

echo "hi, stdout"
echo "hello, stderr" >&2
echo "hi, stdout"

ls -al
cat changelogs.txt

hi, stdout
hi, stdout
total 7160
drwxr-xr-x 6 1000 1000    4096 Jun  3 18:56 .
drwxr-xr-x 7 1000 1000    4096 Jun  1 21:48 ..
-rw-r--r-- 1 1000 1000    1036 May 15 09:59 bug_tracking.txt
-rw-r--r-- 1 1000 1000     799 May 30 12:06 changelogs.txt
drwxr-xr-x 2 1000 1000    4096 May 16 15:11 imgs
drwxr-xr-x 2 1000 1000    4096 May 16 15:11 inputs
drwxr-xr-x 2 1000 1000    4096 Jun  2 20:58 .ipynb_checkpoints
-r-------- 1 1000 1000  123480 Mar 26 09:01 mini_projet_progsysteme_hepia_2014_2015_minix_fs.pdf
-rw-r--r-- 1 1000 1000       0 Mar 28 18:27 planing.txt
-rw-r--r-- 1 1000 1000    1166 Jun  2 08:56 rapport.aux
-rw-r--r-- 1 1000 1000   67308 Jun  2 08:56 rapport.dvi
-rw-r--r-- 1 1000 1000   10621 Jun  2 10:29 rapport.fdb_latexmk
-rw-r--r-- 1 1000 1000   10518 Jun  2 08:56 rapport.fls
-rw-r--r-- 1 root root   43516 Jun  3 18:56 rapport.ipynb
-rw-r--r-- 1 1000 1000   21587 Jun  2 10:29 rapport.log
-rw-r--r-- 1 1000 1000     185 Jun  2 08:56 rapport.out
-rw-r--r-- 1 1000 1000  221174 May 3

hello, stderr
hello, stderr


In [14]:
import time
tic = time.time()
line = True
while True:
    line = bashout.readline()
    if not line:
        break
    sys.stdout.write("%.1fs: %s" %(time.time()-tic, line))
    sys.stdout.flush()

NameError: name 'bashout' is not defined

In [12]:
%%ruby --bg --out ruby_lines
for n in 1...10
    sleep 1
    puts "line #{n}"
    STDOUT.flush
end

Starting job # 0 in a separate thread.


In [13]:
ruby_lines
print(ruby_lines.read())

b'line 1\nline 2\nline 3\nline 4\nline 5\nline 6\nline 7\nline 8\nline 9\n'


In [7]:
a = %octave [1 2; 3 4];
a

ERROR: Line magic function `%octave` not found.


In [ ]:
from oct2py import octave as oc
from scipy import *


In [3]:
y = np.random.normal(0.0, 1.0, 50)
y

array([-1.13538555,  1.00791906,  0.25952187, -0.68861001,  0.39114891,
        0.34604681, -0.89069391,  0.36138425, -0.25793176,  0.69458795,
        3.25618794,  0.50666736,  0.19517959, -0.30505544,  1.00336872,
        1.79529407,  0.50453956,  0.55823819,  0.10980447,  0.16047724,
        1.2841511 ,  0.21979297,  0.83788136,  0.75474388,  0.84902908,
       -1.47913891,  0.80228053, -1.27360998, -0.15440197,  0.7147859 ,
        0.27165588,  0.94971122, -1.35053764,  0.62752365, -1.04206334,
        0.48209045,  0.53110506,  0.04477456,  0.62960961, -0.44647221,
        0.8045767 , -1.03590516,  0.22831115, -0.13553394, -0.89239342,
        1.00166928,  0.94892967,  0.51502012, -0.26304179, -0.20670929])

In [5]:
plt.ylabel("MPG")
auto_df.plot(x="cylinders", y="mpg", style='o')

NameError: name 'plt' is not defined

In [2]:
fig, ax = plt.subplots()
plt.scatter(x, y)

NameError: name 'plt' is not defined

In [1]:
plt.subplot(121)    # parameter indicates 1 rows, 2 col, first figure
plt.scatter(x, y)
plt.subplot(122)
plt.hist(y)

NameError: name 'plt' is not defined

# Tile of my document #

this is a block of text

follwed by a subtitle

 * fgdff
 * ghgfhd
 * [lien...](http://google.ch)

## subtitle ##

continue
### Un subsubtitle ###

$\sum_{i=0}{a}\frac{a^2}{b^3}$

### Exemple de code ###

```python

def add_entry(self, dinode, name, new_node_num):
        """ add a new entry in a dinode (dir)

        :param dinode: inode number of the dir
        :param name: name of the file to be added
        :param new_node_num: inode of the new file
        """
        done = False
        blk = -1
        # TODO increment link de l'inode

        if len(name) > (DIRSIZE - 2):
            raise FileNameError('Error Filename too long')
        if self.lookup_entry(dinode, name):
            raise AddEntryError('Error filename already exist in dir')

        while not done:

            blk += 1
            data_block = self.bmap(dinode, blk)

            if data_block:
                # TODO if new block  bytearray("".ljust(1024, '\x00'))
                self.content = bytearray(self.disk.read_bloc(data_block))

            elif blk < MINIX_ZONESZ ** 2 + MINIX_ZONESZ + 7:
                data_block = self.ialloc_bloc(dinode, blk)
                # empty new block
                self.content = bytearray("".ljust(1024, '\x00'))

            else:
                raise DirFullError('Error too many file in dir: overflow')

            for off in xrange(0, BLOCK_SIZE, DIRSIZE):
                if not struct.unpack_from('H', self.content, off)[0]:
                    struct.pack_into('H', self.content, off, new_node_num)
                    self.content[off + 2:off + DIRSIZE] = name.ljust(DIRSIZE - 2, '\x00')
                    dinode.i_size += DIRSIZE
                    done = True
                    break

        if done:
            self.disk.write_bloc(data_block, self.content)
        else:
            raise AddError('Unable to add entry')
```

[Lien vers google...](https://www.google.com)

In [2]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return a sequence of numbers from start to stop by step.
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __new__(*args, **kwargs) from b

In [8]:
# %load ../minixfs.py

__author__ = 'Sebastien Chassot'
__author_email__ = 'sebastien.chassot@etu.hesge.ch'

__version__ = "1.0.1"
__copyright__ = ""
__licence__ = ""
__status__ = "TP minix fs"

from constantes import *

""" Extract the super block from a block device """
class minix_superbloc(object):

    def __init__(self, blk_device):
        """ Init the super block
        :param blk_device: the block device
        """
        try:
            sb = struct.unpack_from('HHHHHHIHH', blk_device.read_bloc(MINIX_SUPER_BLOCK_NUM))
        except OSError:
            exit("Error unable to read super block")

        self.s_ninodes, self.s_nzones, self.s_imap_blocks, self.s_zmap_blocks, self.s_firstdatazone, \
            self.s_log_zone_size, self.s_max_size, self.s_magic, self.s_state = sb



ImportError: No module named 'constantes'

In [9]:
# %load ../constantes.py

__author__ = 'Sebastien Chassot'
__author_email__ = 'sebastien.chassot@etu.hesge.ch'

__version__ = "1.0.1"
__copyright__ = ""
__licence__ = ""
__status__ = "TP minix fs"

import sys
import struct
import os
import time
from stat import *
from bitarray import *
import logging as log
import hexdump

#block size in bytes
BLOCK_SIZE=1024
#on which block number is the superbloc
MINIX_SUPER_BLOCK_NUM=1
#that's in octets units
MINIX_SUPER_BLOCK_SIZE=20
MINIX_ROOT_INO=1
#zone number are encoded with 2 bytes
#hence 512 possible indirect zones in a bloc
MINIX_ZONESZ=int(BLOCK_SIZE/2)
DIRSIZE=16
MAXOPENFILE=10
MINIX_DIR_ENTRIES_PER_BLOCK=BLOCK_SIZE/DIRSIZE
#inode types
I_DIRECTORY=0o040000
I_REGULAR=0o100000
#inode structure size in bytes
INODE_SIZE=32
MINIX_INODE_PER_BLOCK=BLOCK_SIZE/INODE_SIZE


ImportError: No module named 'bitarray'

In [ ]:
# %load ../bloc_device.py
# emulate a simple bloc device using a file
# reading it only by bloc units

__author__ = 'Sebastien Chassot'
__author_email__ = 'sebastien.chassot@etu.hesge.ch'

__version__ = "1.0.1"
__copyright__ = ""
__licence__ = ""
__status__ = "TP minix fs"


from minix_superbloc import *
import socket
import random as rand
import logging as log

log.basicConfig(format='%(levelname)s:%(message)s', level=log.INFO)


class bloc_device(object):
    """ Class block device """

    def __init__(self, blksize, pathname):
        """ Init a new block device """
        self.blksize = blksize

        # with open(pathname, 'br') as self.fd:
        try:
            self.fd = open(pathname, 'r+b')
        except OSError:
            sys.exit("Error unable to open file system")

        self.super_block = minix_superbloc(self)
        log.info("file system opened successfully")

    def __del__(self):
        """ Close properly the block device """
        new_sb = bytearray("".ljust(1024, '\x00'))
        clean_state = 1
        sb = struct.pack('HHHHHHIHH', self.super_block.s_ninodes, self.super_block.s_nzones,
                self.super_block.s_imap_blocks, self.super_block.s_zmap_blocks, self.super_block.s_firstdatazone,
                self.super_block.s_log_zone_size, self.super_block.s_max_size, self.super_block.s_magic, clean_state)
        new_sb[:sb.__len__()] = sb
        log.info("file system cleanly closed")
        # self.write_bloc(MINIX_SUPER_BLOCK_NUM, new_sb)
        self.fd.close()

    def read_bloc(self, bloc_num, numofblk=1):
        """ Read n block from block device
        :param bloc_num: block number to be read
        :param numofblk: number of block to be read
        :return: the buffer
        """
        # TODO test fs size and bloc_num comparison
        try:
            self.fd.seek(bloc_num*self.blksize)
            buff = self.fd.read(int(numofblk*self.blksize))
        except OSError, err:
            print(err)

        return buff

    def write_bloc(self, bloc_num, bloc):
        """ Write a block to block device
        :param bloc_num: block number to be written
        :param bloc: buffer to be written
        :return: nb of bytes actually written
        """
        try:
            self.fd.seek(bloc_num*self.blksize)
            n = self.fd.write(bloc)
        except OSError, err:
            print(err)

        return n


class remote_bloc_device(object):
    """ Class remote block device

        This class connect to a remote bloc server and
        read/write commands are passed through a
        TCP socket
    """

    def __init__(self, blksize, host="localhost", port=1234):
        self.blksize = blksize
        self.requests = []
        self.responses = []
        self.fd = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            self.fd.connect((socket.gethostbyname(host), port))
        except socket.error:
            print("Couldnt connect to the block server")
            sys.exit("Error unable to connect to block server")

        self.super_block = minix_superbloc(self)
        log.info("remote file system opened successfully")

    def __del__(self):
        """ Cleanly close the socket """
        new_sb = bytearray("".ljust(1024, '\x00'))
        clean_state = 1
        sb = struct.pack('HHHHHHIHH', self.super_block.s_ninodes, self.super_block.s_nzones,
                self.super_block.s_imap_blocks, self.super_block.s_zmap_blocks, self.super_block.s_firstdatazone,
                self.super_block.s_log_zone_size, self.super_block.s_max_size, self.super_block.s_magic, clean_state)
        new_sb[:sb.__len__()] = sb
        self.close_connection()

    def read_bloc(self, bloc_num, numofbloc=1):
        """ Read n block from block device server

        :param bloc_num: the bloc number
        :param numofbloc: number of block to be read
        :return: the response
        """
        magic_req = int('76767676', 16)
        magic_resp = int('87878787', 16)
        rw_type = 0
        rand.seed(None)  # None = current system time
        handle = rand.randint(0, 2**32)
        offset = bloc_num*self.blksize
        length = numofbloc*self.blksize
        to_send = 0
        header_size = struct.calcsize('!IIIII')

        #
        self.requests.insert(0, struct.pack('!IIIII', magic_req, rw_type, handle, offset, length))
        done = False
        buff = ""

        while not done:
            # send the header
            while to_send < header_size:
                sent = self.fd.send(self.requests[0][to_send:])
                if sent == 0:
                    raise RuntimeError("socket connection broken")
                to_send += sent

            # read response
            response = ""
            response_size = struct.calcsize('!III')
            to_recv = 0

            while to_recv < response_size:
                b = self.fd.recv(response_size-to_recv)
                if b == '':
                    raise RuntimeError("socket connection broken")

                response += b
                to_recv += len(b)

            h = struct.unpack('!III', response)

            if h == (magic_resp, 0, handle):
            
                buff = ""
                to_recv = 0
                while to_recv < length:
                    b = self.fd.recv(length-to_recv)
                    if b == '':
                        raise RuntimeError("socket connection broken")
                    buff += b
                    to_recv += len(b)

                # remove request from fifo
                # self.requests.pop[0]
                done = True

            else:
                raise RuntimeError("fail to read response")

        return buff

    def write_bloc(self, bloc_num, bloc):
        """ Write block from block device server

        :param bloc_num: the bloc number
        :param bloc: buffer to be written
        """
        magic = int('76767676', 16)
        magic_resp = int('87878787', 16)
        rw_type = 1
        rand.seed(None)  # None = current system time
        handle = rand.randint(0, 2**32)
        offset = bloc_num*self.blksize

        # Can't write block not eq to BLOCK_SIZE it's a block server after all ?!
        if bloc.__len__() != self.blksize:
            log.error("Block isn't equal to block size")
            raise BlockSizeError("Block isn't equal to block size")

        to_send = 0
        header = struct.pack('!IIIII', magic, rw_type, handle, offset, self.blksize)
        self.requests.insert(0, header+bloc)
        # TODO consolider while send
        while to_send < len(header+bloc):
            sent = self.fd.send(self.requests[0][to_send:])
            if sent == 0:
                raise RuntimeError("socket connection broken")
            to_send += sent

        # read response
        responce = ''
        response_size = struct.calcsize('!III')
        to_recv = 0

        while to_recv < response_size:
            b = self.fd.recv(response_size-to_recv)
            if b == '':
                raise RuntimeError("socket connection broken")
            responce += b
            to_recv += len(b)

        h = struct.unpack('!III', responce)
        # TODO resend, close and pop
        # self.requests.pop[0]

    def close_connection(self):
        """ close properly the socket """

        try:
            self.fd.close()
            log.info("socket cleanly closed")
        except:
            log.error("Error closing socket")


class MyBaseException(Exception):
    """ Class minixfs exceptions  """
    def __init__(self, message):
        super(MyBaseException, self).__init__(message)
        self.message = message


class BlockSizeError(MyBaseException):
    pass


In [8]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [3]:
!ls -al  ..

total 69572
drwxr-xr-x  7 1000 1000     4096 Jun  1 21:48 .
drwxr-xr-x 22 root root     4096 Jun  1 22:55 ..
drwxr-xr-x  3 1000 1000     4096 Mar 29 11:58 bitarray.unused
-rw-r--r--  1 1000 1000     7750 May 30 18:29 bloc_device.py
-rw-r--r--  1 1000 1000     8007 May 30 18:32 bloc_device.pyc
-rw-r--r--  1 1000 1000    17010 May  4 17:19 code_tester2.tgz
-rw-r--r--  1 1000 1000      821 May 10 18:06 constantes.py
-rw-r--r--  1 1000 1000      988 May 30 17:16 constantes.pyc
drwxr-xr-x  6 1000 1000     4096 Jun  1 23:14 docs
drwxr-xr-x  8 1000 1000     4096 Jun  1 23:05 .git
-rw-r--r--  1 1000 1000     2301 May 17 09:32 .gitignore
-rw-r--r--  1 1000 1000    12894 Mar 23 17:37 hexdump.py
-rw-r--r--  1 1000 1000    13340 May 30 17:16 hexdump.pyc
drwxr-xr-x  5 1000 1000     4096 May 30 19:17 .idea
-rw-r--r--  1 1000 1000      176 May  9 10:45 Makefile
-rw-r--r--  1 1000 1000 20971520 May 24 09:45 minixfs_lab1.img
-rw-r--r--  1 1000 1000 20971520 May 24 09:45 minixfs_lab1.img.org
-rw-r--r-- 

In [4]:
!cat /etc/resolv.conf


# Generated by resolvconf
search v.cablecom.net
nameserver 62.2.17.60
nameserver 62.2.24.162
